services:
  app:
    image: nitro_generator_checker
    build:
      context: .
      args:
        - GID=${GID:-1000}
        - UID=${UID:-1000}
    tty: true
    volumes:
      - ./config.toml:/app/config.toml
      - ./nitro_codes.txt:/app/nitro_codes.txt
